# Generated by nixos-generate-config on P22725.
# Intel CPU, UEFI boot, NVIDIA GPU (driver configured via services.mediaServer.gpu in default.nix).
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "vmd" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0c61f90a-13f2-4b07-90b6-573d6a42e9ba";
      fsType = "btrfs";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/0c61f90a-13f2-4b07-90b6-573d6a42e9ba";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/0c61f90a-13f2-4b07-90b6-573d6a42e9ba";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6CFD-B1F9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # Media storage: two 4TB HDDs formatted as BTRFS RAID1.
  fileSystems."/srv/media" =
    { device = "UUID=fb3d123f-9813-403b-8a4e-645de1b7b61f";
      fsType = "btrfs";
      options = [ "compress=zstd" "autodefrag" "nofail" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/bf5c414a-73b1-4d3d-b85c-e901310f9857"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.nvidia.package = pkgs.nvidiaPackages.legacy_580;
}
