# Generated by nixos-generate-config on P27691 (retired SolidWorks PC).
# Intel CPU, UEFI boot, NVIDIA GPU (driver configured via services.mediaServer.gpu in default.nix).
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "vmd" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # OS drive (BTRFS with subvolumes — pre-existing from NixOS install)
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/67a5f5ec-653c-4155-b8c2-c14febd2474a";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/67a5f5ec-653c-4155-b8c2-c14febd2474a";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C96E-05C9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # Media storage: two 4TB SSDs formatted as BTRFS RAID1.
  #
  # One-time setup (run on the machine before first deploy):
  #   1. Find the drive IDs:
  #        ls /dev/disk/by-id/ | grep -v part
  #   2. Format as BTRFS RAID1 (mirrors data + metadata across both drives):
  #        mkfs.btrfs -L media -m raid1 -d raid1 \
  #          /dev/disk/by-id/<ssd1> /dev/disk/by-id/<ssd2>
  #   3. Get the UUID:
  #        blkid | grep 'LABEL="media"'
  #   4. Replace FILL_IN_AFTER_MKFS below with that UUID, then push.
  #
  # If one drive fails later:
  #   btrfs replace start /dev/disk/by-id/<replacement> /srv/media
  #
  fileSystems."/srv/media" =
    { device = "UUID=9098d112-a4ca-4af0-9da5-2e3e6aa0da1b";
      fsType = "btrfs";
      options = [ "compress=zstd" "autodefrag" "nofail" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/009d93cb-6277-4529-b375-e56349df619a"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
