'use strict';

/**
 * Team alias resolution. Lookup is two-pass:
 *   1. exact normalized match
 *   2. word/prefix fallback (handles "Yankees" → "New York Yankees")
 *
 * The aliases are intentionally hand-curated for the sports this M3U
 * provider currently carries (US + major European soccer). New leagues
 * can be added by appending a `key: [aliases]` entry.
 *
 * Keys are the normalized team names as exposed by ESPN (e.g. "new york yankees").
 */
export const ALIASES = {
  // MLB
  'new york yankees': ['yankees', 'nyy'],
  'boston red sox': ['red sox'],
  'baltimore orioles': ['orioles'],
  'tampa bay rays': ['rays'],
  'toronto blue jays': ['blue jays', 'jays'],
  'chicago white sox': ['white sox'],
  'cleveland guardians': ['guardians'],
  'detroit tigers': ['tigers'],
  'kansas city royals': ['royals'],
  'minnesota twins': ['twins'],
   'chicago cubs': ['cubs', 'chc'],
   'cincinnati reds': ['reds', 'cin'],
  'milwaukee brewers': ['brewers'],
  'cleveland indians': ['indians'], // historical alias for guardians
  'pittsburgh pirates': ['pirates'],
  'st. louis cardinals': ['cardinals'],
  'atlanta braves': ['braves'],
  'miami marlins': ['marlins'],
  'new york mets': ['mets'],
  'philadelphia phillies': ['phillies'],
  'washington nationals': ['nationals'],
  'oakland athletics': ['athletics', 'as'],
  'los angeles angels': ['angels', 'laa'],
  'houston astros': ['astros'],
  'seattle mariners': ['mariners'],
  'texas rangers': ['rangers'],
  'arizona diamondbacks': ['diamondbacks', 'dbacks'],
  'colorado rockies': ['rockies'],
  'los angeles dodgers': ['dodgers'],
  'san diego padres': ['padres'],
  'san francisco giants': ['giants'],

  // NFL (abbreviated forms the M3U commonly uses)
  'arizona cardinals': ['cardinals'],
  'atlanta falcons': ['falcons'],
  'baltimore ravens': ['ravens'],
  'buffalo bills': ['bills'],
  'carolina panthers': ['panthers'],
  'chicago bears': ['bears'],
  'cincinnati bengals': ['bengals'],
  'cleveland browns': ['browns'],
  'dallas cowboys': ['cowboys'],
  'denver broncos': ['broncos'],
  'detroit lions': ['lions'],
  'green bay packers': ['packers'],
  'houston texans': ['texans'],
  'indianapolis colts': ['colts'],
  'jacksonville jaguars': ['jaguars'],
  'kansas city chiefs': ['chiefs'],
  'las vegas raiders': ['raiders'],
  'los angeles chargers': ['chargers'],
  'los angeles rams': ['rams'],
  'miami dolphins': ['dolphins'],
  'minnesota vikings': ['vikings'],
  'new england patriots': ['patriots'],
  'new orleans saints': ['saints'],
  'new york giants': ['giants'],
  'philadelphia eagles': ['eagles'],
  'pittsburgh steelers': ['steelers'],
  'san francisco 49ers': ['49ers', 'niners'],
  'seattle seahawks': ['seahawks'],
  'tampa bay buccaneers': ['buccaneers', 'bucs'],
  'tennessee titans': ['titans'],
  'washington commanders': ['commanders', 'football team'],
  'washington football team': ['washington', 'wft'],
  'los angeles chargers': ['chargers', 'lac'],
  'las vegas raiders': ['raiders'],
  'oakland raiders': ['raiders'],

  // NBA
  'boston celtics': ['celtics'],
  'brooklyn nets': ['nets'],
  'new york knicks': ['knicks'],
  'philadelphia 76ers': ['76ers', 'sixers'],
  'toronto raptors': ['raptors'],
  'chicago bulls': ['bulls'],
  'cleveland cavaliers': ['cavaliers', 'cavs'],
  'detroit pistons': ['pistons'],
  'indiana pacers': ['pacers'],
  'milwaukee bucks': ['bucks'],
  'atlanta hawks': ['hawks'],
  'charlotte hornets': ['hornets'],
  'miami heat': ['heat'],
  'orlando magic': ['magic'],
  'washington wizards': ['wizards'],
  'denver nuggets': ['nuggets'],
  'minnesota timberwolves': ['timberwolves', 'wolves'],
  'oklahoma city thunder': ['thunder', 'okc'],
  'portland trail blazers': ['trail blazers', 'blazers'],
  'utah jazz': ['jazz'],
  'golden state warriors': ['warriors', 'gsw'],
  'los angeles lakers': ['lakers'],
  'los angeles clippers': ['clippers'],
  'phoenix suns': ['suns'],
  'sacramento kings': ['kings'],
  'dallas mavericks': ['mavericks', 'mavs'],
  'houston rockets': ['rockets'],
  'memphis grizzlies': ['grizzlies'],
  'new orleans pelicans': ['pelicans'],
  'san antonio spurs': ['spurs'],

  // NHL
  'boston bruins': ['bruins'],
  'buffalo sabres': ['sabres'],
  'detroit red wings': ['red wings'],
  'florida panthers': ['panthers'],
  'montreal canadiens': ['canadiens', 'habs'],
  'ottawa senators': ['senators'],
  'tampa bay lightning': ['lightning'],
  'toronto maple leafs': ['maple leafs', 'leafs'],
  'carolina hurricanes': ['hurricanes'],
  'columbus blue jackets': ['blue jackets'],
  'new jersey devils': ['devils'],
  'new york islanders': ['islanders'],
  'new york rangers': ['rangers'],
  'philadelphia flyers': ['flyers'],
  'pittsburgh penguins': ['penguins'],
  'washington capitals': ['capitals', 'caps'],
  'chicago blackhawks': ['blackhawks'],
  'colorado avalanche': ['avalanche'],
  'dallas stars': ['stars'],
  'minnesota wild': ['wild'],
  'nashville predators': ['predators'],
  'st. louis blues': ['blues'],
  'utah hockey club': ['utah', 'hc'],
  'winnipeg jets': ['jets'],
  'anaheim ducks': ['ducks'],
  'calgary flames': ['flames'],
  'edmonton oilers': ['oilers'],
  'los angeles kings': ['kings'],
  'san jose sharks': ['sharks'],
  'seattle kraken': ['kraken'],
  'vancouver canucks': ['canucks'],
  'vegas golden knights': ['vegas', 'golden knights', 'vgk'],

  // Soccer
  'manchester united': ['man utd', 'man united', 'united'],
  'manchester city': ['man city'],
  'tottenham hotspur': ['spurs', 'tottenham'],
  'liverpool': ['liverpool fc'],
  'arsenal': ['arsenal fc', 'gunners'],
  'chelsea': ['chelsea fc', 'blues'],
  'real madrid': ['madrid'],
  'atletico madrid': ['atleti', 'atlético'],
  'barcelona': ['barca', 'fc barcelona'],
  'bayern munich': ['bayern'],
  'borussia dortmund': ['dortmund', 'bvb'],
  'juventus': ['juve'],
  'ac milan': ['milan'],
  'internazionale': ['inter', 'inter milan'],
  'paris saint-germain': ['psg'],
  'olympique de marseille': ['marseille', 'om'],
};
